server:
  port: 80
  
spring:
    active:
    - app
    eureka: 
     client: 
       register-with-eureka: false #获取服务提供方地址,本身不注册进eureka服务
       service-url: 
         defaultZone: http://eureka7001.com:7001/eureka/
    
---
server:
  port: 90
  
spring:
  profiles: dev
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8002   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

---
server:
  port: 70
  
spring:
  profiles: app
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7002.com:7002/eureka/
  instance:
    instance-id: microservicecloud-dept8001   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

  
